function draw_csl_simi_by_type()
    fid = fopen('./data/cross-site-linking/username_simi_1.csv', 'rt');
    C = textscan(fid, '%f %s %f', 'Delimiter', ',', 'HeaderLines', 1);
    fclose(fid);
    simi_1 = C{1};
    fid = fopen('./data/cross-site-linking/username_simi_3.csv', 'rt');
    C = textscan(fid, '%f %s %f', 'Delimiter', ',', 'HeaderLines', 1);
    fclose(fid);
    simi_3 = C{1};
    figure(1);
    h1 = cdfplot(simi_1);
    set(h1, 'color', 'b', 'LineStyle', '-', 'LineWidth', 2);
    hold on;
    h3 = cdfplot(simi_3);
    set(h3, 'color', 'r', 'LineStyle', '--', 'LineWidth', 2);
    set(gca, 'yticklabel', cellstr(num2str(get(gca,'ytick')'*100)));
    set(gca, 'FontSize', 12);
    xlabel('Similarity','FontSize',20);
    ylabel('Percentage(%)','FontSize',20);
    legend('TW only', 'Both', 'Location', 'NorthWest');
    set(legend, 'FontSize', 20);
    title('');
    grid off;
    print('./results/csl/CDF_similarity_username_by_type.eps', '-depsc');
    
    fid = fopen('./data/cross-site-linking/name_simi_1.csv', 'rt');
    C = textscan(fid, '%f %s %f', 'Delimiter', ',', 'HeaderLines', 1);
    fclose(fid);
    simi_1 = C{1};
    fid = fopen('./data/cross-site-linking/name_simi_3.csv', 'rt');
    C = textscan(fid, '%f %s %f', 'Delimiter', ',', 'HeaderLines', 1);
    fclose(fid);
    simi_3 = C{1};
    figure(2);
    h1 = cdfplot(simi_1);
    set(h1, 'color', 'b', 'LineStyle', '-', 'LineWidth', 2);
    hold on;
    h3 = cdfplot(simi_3);
    set(h3, 'color', 'r', 'LineStyle', '--', 'LineWidth', 2);
    set(gca, 'yticklabel', cellstr(num2str(get(gca,'ytick')'*100)));
    set(gca, 'FontSize', 12);
    xlabel('Similarity','FontSize',20);
    ylabel('Percentage(%)','FontSize',20);
    legend('TW only', 'Both', 'Location', 'NorthWest');
    set(legend, 'FontSize', 20);
    title('');
    grid off;
    print('./results/csl/CDF_similarity_name_by_type.eps', '-depsc');
    
    fid = fopen('./data/cross-site-linking/bio_simi_1.csv', 'rt');
    C = textscan(fid, '%f %s %f', 'Delimiter', ',', 'HeaderLines', 1);
    fclose(fid);
    simi_1 = C{1};
    fid = fopen('./data/cross-site-linking/bio_simi_3.csv', 'rt');
    C = textscan(fid, '%f %s %f', 'Delimiter', ',', 'HeaderLines', 1);
    fclose(fid);
    simi_3 = C{1};
    figure(3);
    h1 = cdfplot(simi_1);
    set(h1, 'color', 'b', 'LineStyle', '-', 'LineWidth', 2);
    hold on;
    h3 = cdfplot(simi_3);
    set(h3, 'color', 'r', 'LineStyle', '--', 'LineWidth', 2);
    set(gca, 'yticklabel', cellstr(num2str(get(gca,'ytick')'*100)));
    set(gca, 'FontSize', 12);
    xlabel('Similarity','FontSize',20);
    ylabel('Percentage(%)','FontSize',20);
    legend('TW only', 'Both', 'Location', 'NorthWest');
    set(legend, 'FontSize', 20);
    title('');
    grid off;
    print('./results/csl/CDF_similarity_bio_by_type.eps', '-depsc');
end