function draw_csl_in_graph()
    dataset_0 = csvread('./data/cross-site-linking/user_degree_in_graph_0.csv', 1, 1);
    dataset_1 = csvread('./data/cross-site-linking/user_degree_in_graph_1.csv', 1, 1);
    dataset_2 = csvread('./data/cross-site-linking/user_degree_in_graph_2.csv', 1, 1);
    dataset_3 = csvread('./data/cross-site-linking/user_degree_in_graph_3.csv', 1, 1);
    
    figure(1);
    h = cdfplot(dataset_0(:,1));
    set(h, 'color', 'k', 'LineStyle', '-', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_1(:,1));
    set(h, 'color', 'r', 'LineStyle', '--', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_2(:,1));
    set(h, 'color', 'g', 'LineStyle', '-.', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_3(:,1));
    set(h, 'color', 'b', 'LineStyle', ':', 'LineWidth', 2);
    xlim([0, 100]);
    set(gca, 'yticklabel', cellstr(num2str(get(gca,'ytick')'*100)));
    set(gca, 'FontSize', 12);
    xlabel('In-degree','FontSize',20);
    ylabel('Percentage(%)','FontSize',20);
    legend('Neither', 'TW only', 'FB only', 'Both', 'Location', 'SouthEast');
    set(legend, 'FontSize', 20);
    title('');
    grid off;
    print('./results/csl/CDF_in_degree_in_graph_csl.eps', '-depsc');
    
    figure(2);
    h = cdfplot(dataset_0(:,2));
    set(h, 'color', 'k', 'LineStyle', '-', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_1(:,2));
    set(h, 'color', 'r', 'LineStyle', '--', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_2(:,2));
    set(h, 'color', 'g', 'LineStyle', '-.', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_3(:,2));
    set(h, 'color', 'b', 'LineStyle', ':', 'LineWidth', 2);
    xlim([0, 100]);
    set(gca, 'yticklabel', cellstr(num2str(get(gca,'ytick')'*100)));
    set(gca, 'FontSize', 12);
    xlabel('Out-degree','FontSize',20);
    ylabel('Percentage(%)','FontSize',20);
    legend('Neither', 'TW only', 'FB only', 'Both', 'Location', 'SouthEast');
    set(legend, 'FontSize', 20);
    title('');
    grid off;
    print('./results/csl/CDF_out_degree_in_graph_csl.eps', '-depsc');
    
    figure(3);
    h = cdfplot(dataset_0(:,3));
    set(h, 'color', 'k', 'LineStyle', '-', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_1(:,3));
    set(h, 'color', 'r', 'LineStyle', '--', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_2(:,3));
    set(h, 'color', 'g', 'LineStyle', '-.', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_3(:,3));
    set(h, 'color', 'b', 'LineStyle', ':', 'LineWidth', 2);
    set(gca,'XScale','log');
    xlim([0.1 10]);
    set(gca, 'yticklabel', cellstr(num2str(get(gca,'ytick')'*100)));
    set(gca, 'FontSize', 12);
    xlabel('Balance','FontSize',20);
    ylabel('Percentage(%)','FontSize',20);
    legend('Neither', 'TW only', 'FB only', 'Both', 'Location', 'SouthEast');
    set(legend, 'FontSize', 20);
    title('');
    grid off;
    print('./results/csl/CDF_balance_in_graph_csl.eps', '-depsc');
    
    figure(4);
    h = cdfplot(dataset_0(:,4));
    set(h, 'color', 'k', 'LineStyle', '-', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_1(:,4));
    set(h, 'color', 'r', 'LineStyle', '--', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_2(:,4));
    set(h, 'color', 'g', 'LineStyle', '-.', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_3(:,4));
    set(h, 'color', 'b', 'LineStyle', ':', 'LineWidth', 2);
    set(gca, 'yticklabel', cellstr(num2str(get(gca,'ytick')'*100)));
    set(gca, 'FontSize', 12);
    xlabel('Reciprocity','FontSize',20);
    ylabel('Percentage(%)','FontSize',20);
    legend('Neither', 'TW only', 'FB only', 'Both', 'Location', 'SouthEast');
    set(legend, 'FontSize', 20);
    title('');
    grid off;
    print('./results/csl/CDF_reciprocity_in_graph_csl.eps', '-depsc');
    
    figure(5);
    h = cdfplot(dataset_0(:,1) + dataset_0(:,2));
    set(h, 'color', 'k', 'LineStyle', '-', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_1(:,1) + dataset_1(:,2));
    set(h, 'color', 'r', 'LineStyle', '--', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_2(:,1) + dataset_2(:,2));
    set(h, 'color', 'g', 'LineStyle', '-.', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_3(:,1) + dataset_3(:,2));
    set(h, 'color', 'b', 'LineStyle', ':', 'LineWidth', 2);
    xlim([0, 200]);
    set(gca, 'yticklabel', cellstr(num2str(get(gca,'ytick')'*100)));
    set(gca, 'FontSize', 12);
    xlabel('Degree','FontSize',20);
    ylabel('Percentage(%)','FontSize',20);
    legend('Neither', 'TW only', 'FB only', 'Both', 'Location', 'SouthEast');
    set(legend, 'FontSize', 20);
    title('');
    grid off;
    print('./results/csl/CDF_degree_in_graph_csl.eps', '-depsc');

end