function draw_csl_attr()
    dataset_0 = csvread('./data/cross-site-linking/user_attr_0.csv', 1, 2);
    dataset_1 = csvread('./data/cross-site-linking/user_attr_1.csv', 1, 2);
    dataset_2 = csvread('./data/cross-site-linking/user_attr_2.csv', 1, 2);
    dataset_3 = csvread('./data/cross-site-linking/user_attr_3.csv', 1, 2);
    
    figure(1);
    h = cdfplot(dataset_0(:,1));
    set(h, 'color', 'k', 'LineStyle', '-', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_1(:,1));
    set(h, 'color', 'r', 'LineStyle', '--', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_2(:,1));
    set(h, 'color', 'g', 'LineStyle', '-.', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_3(:,1));
    set(h, 'color', 'b', 'LineStyle', ':', 'LineWidth', 2);
    set(gca, 'yticklabel', cellstr(num2str(get(gca,'ytick')'*100)));
    set(gca, 'FontSize', 12);
    xlabel('Clustering Coefficient','FontSize',20);
    ylabel('Percentage(%)','FontSize',20);
    legend('Neither', 'TW only', 'FB only', 'Both', 'Location', 'SouthEast');
    set(legend, 'FontSize', 20);
    title('');
    grid off;
    print('./results/csl/CDF_CC_csl.eps', '-depsc');
    
    figure(2);
    h = cdfplot(dataset_0(:,2));
    set(h, 'color', 'k', 'LineStyle', '-', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_1(:,2));
    set(h, 'color', 'r', 'LineStyle', '--', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_2(:,2));
    set(h, 'color', 'g', 'LineStyle', '-.', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_3(:,2));
    set(h, 'color', 'b', 'LineStyle', ':', 'LineWidth', 2);
    xlim([0, 300]);
    set(gca, 'yticklabel', cellstr(num2str(get(gca,'ytick')'*100)));
    set(gca, 'FontSize', 12);
    xlabel('In-degree','FontSize',20);
    ylabel('Percentage(%)','FontSize',20);
    legend('Neither', 'TW only', 'FB only', 'Both', 'Location', 'SouthEast');
    set(legend, 'FontSize', 20);
    title('');
    grid off;
    print('./results/csl/CDF_in_degree_csl.eps', '-depsc');
    
    figure(3);
    h = cdfplot(dataset_0(:,3));
    set(h, 'color', 'k', 'LineStyle', '-', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_1(:,3));
    set(h, 'color', 'r', 'LineStyle', '--', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_2(:,3));
    set(h, 'color', 'g', 'LineStyle', '-.', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_3(:,3));
    set(h, 'color', 'b', 'LineStyle', ':', 'LineWidth', 2);
    xlim([0, 300]);
    set(gca, 'yticklabel', cellstr(num2str(get(gca,'ytick')'*100)));
    set(gca, 'FontSize', 12);
    xlabel('Out-degree','FontSize',20);
    ylabel('Percentage(%)','FontSize',20);
    legend('Neither', 'TW only', 'FB only', 'Both', 'Location', 'SouthEast');
    set(legend, 'FontSize', 20);
    title('');
    grid off;
    print('./results/csl/CDF_out_degree_csl.eps', '-depsc');
    
    figure(4);
    h = cdfplot(dataset_0(:,4));
    set(h, 'color', 'k', 'LineStyle', '-', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_1(:,4));
    set(h, 'color', 'r', 'LineStyle', '--', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_2(:,4));
    set(h, 'color', 'g', 'LineStyle', '-.', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_3(:,4));
    set(h, 'color', 'b', 'LineStyle', ':', 'LineWidth', 2);
    xlim([0, 2]);
    set(gca, 'yticklabel', cellstr(num2str(get(gca,'ytick')'*100)));
    set(gca, 'FontSize', 12);
    xlabel('Balance','FontSize',20);
    ylabel('Percentage(%)','FontSize',20);
    legend('Neither', 'TW only', 'FB only', 'Both', 'Location', 'SouthEast');
    set(legend, 'FontSize', 20);
    title('');
    grid off;
    print('./results/csl/CDF_balance_csl.eps', '-depsc');
    
    figure(5);
    h = cdfplot(dataset_0(:,5));
    set(h, 'color', 'k', 'LineStyle', '-', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_1(:,5));
    set(h, 'color', 'r', 'LineStyle', '--', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_2(:,5));
    set(h, 'color', 'g', 'LineStyle', '-.', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_3(:,5));
    set(h, 'color', 'b', 'LineStyle', ':', 'LineWidth', 2);
    set(gca, 'yticklabel', cellstr(num2str(get(gca,'ytick')'*100)));
    set(gca, 'FontSize', 12);
    xlabel('Reciprocity','FontSize',20);
    ylabel('Percentage(%)','FontSize',20);
    legend('Neither', 'TW only', 'FB only', 'Both', 'Location', 'SouthEast');
    set(legend, 'FontSize', 20);
    title('');
    grid off;
    print('./results/csl/CDF_reciprocity_csl.eps', '-depsc');
    
    figure(6);
    h = cdfplot(dataset_0(:,6));
    set(h, 'color', 'k', 'LineStyle', '-', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_1(:,6));
    set(h, 'color', 'r', 'LineStyle', '--', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_2(:,6));
    set(h, 'color', 'g', 'LineStyle', '-.', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_3(:,6));
    set(h, 'color', 'b', 'LineStyle', ':', 'LineWidth', 2);
    xlim([0 1e-5]);
    set(gca, 'yticklabel', cellstr(num2str(get(gca,'ytick')'*100)));
    set(gca, 'FontSize', 12);
    xlabel('PageRank','FontSize',20);
    ylabel('Percentage(%)','FontSize',20);
    legend('Neither', 'TW only', 'FB only', 'Both', 'Location', 'SouthEast');
    set(legend, 'FontSize', 20);
    title('');
    grid off;
    print('./results/csl/CDF_pagerank_csl.eps', '-depsc');
    
    figure(7);
    h = cdfplot(dataset_0(:,9));
    set(h, 'color', 'k', 'LineStyle', '-', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_1(:,9));
    set(h, 'color', 'r', 'LineStyle', '--', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_2(:,9));
    set(h, 'color', 'g', 'LineStyle', '-.', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_3(:,9));
    set(h, 'color', 'b', 'LineStyle', ':', 'LineWidth', 2);
    xlim([0 20]);
    set(gca, 'yticklabel', cellstr(num2str(get(gca,'ytick')'*100)));
    set(gca, 'FontSize', 12);
    xlabel('Number of Highlights','FontSize',20);
    ylabel('Percentage(%)','FontSize',20);
    legend('Neither', 'TW only', 'FB only', 'Both', 'Location', 'SouthEast');
    set(legend, 'FontSize', 20);
    title('');
    grid off;
    print('./results/csl/CDF_highlights_csl.eps', '-depsc');
    
    figure(8);
    h = cdfplot(dataset_0(:,10));
    set(h, 'color', 'k', 'LineStyle', '-', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_1(:,10));
    set(h, 'color', 'r', 'LineStyle', '--', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_2(:,10));
    set(h, 'color', 'g', 'LineStyle', '-.', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_3(:,10));
    set(h, 'color', 'b', 'LineStyle', ':', 'LineWidth', 2);
    xlim([0 30]);
    set(gca, 'yticklabel', cellstr(num2str(get(gca,'ytick')'*100)));
    set(gca, 'FontSize', 12);
    xlabel('Number of Posts','FontSize',20);
    ylabel('Percentage(%)','FontSize',20);
    legend('Neither', 'TW only', 'FB only', 'Both', 'Location', 'SouthEast');
    set(legend, 'FontSize', 20);
    title('');
    grid off;
    print('./results/csl/CDF_posts_csl.eps', '-depsc');
    
    figure(9);
    h = cdfplot(dataset_0(:,11));
    set(h, 'color', 'k', 'LineStyle', '-', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_1(:,11));
    set(h, 'color', 'r', 'LineStyle', '--', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_2(:,11));
    set(h, 'color', 'g', 'LineStyle', '-.', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_3(:,11));
    set(h, 'color', 'b', 'LineStyle', ':', 'LineWidth', 2);
    xlim([0 80]);
    set(gca, 'yticklabel', cellstr(num2str(get(gca,'ytick')'*100)));
    set(gca, 'FontSize', 12);
    xlabel('Number of Recommends','FontSize',20);
    ylabel('Percentage(%)','FontSize',20);
    legend('Neither', 'TW only', 'FB only', 'Both', 'Location', 'SouthEast');
    set(legend, 'FontSize', 20);
    title('');
    grid off;
    print('./results/csl/CDF_recommends_csl.eps', '-depsc');
    
    figure(10);
    h = cdfplot(dataset_0(:,12));
    set(h, 'color', 'k', 'LineStyle', '-', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_1(:,12));
    set(h, 'color', 'r', 'LineStyle', '--', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_2(:,12));
    set(h, 'color', 'g', 'LineStyle', '-.', 'LineWidth', 2);
    hold on;
    h = cdfplot(dataset_3(:,12));
    set(h, 'color', 'b', 'LineStyle', ':', 'LineWidth', 2);
    xlim([0 15]);
    set(gca, 'yticklabel', cellstr(num2str(get(gca,'ytick')'*100)));
    set(gca, 'FontSize', 12);
    xlabel('Number of responses','FontSize',20);
    ylabel('Percentage(%)','FontSize',20);
    legend('Neither', 'TW only', 'FB only', 'Both', 'Location', 'SouthEast');
    set(legend, 'FontSize', 20);
    title('');
    grid off;
    print('./results/csl/CDF_responses_csl.eps', '-depsc');
end